name:                kip
version:             0.1.0.0
github:              "joom/kip"
license:             MIT
author:              "Joomy Korkut"
maintainer:          "joomy@cattheory.com"
copyright:           "2021 Joomy Korkut"

extra-source-files:
- README.md

description:          A programming language based on grammatical cases of Turkish. 

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  extra-libraries: foma
  c-sources: c/morphology.c

executables:
  kip:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kip
    - haskeline
